CONFIG_ZMK_USB=n # ZMK_USB is only allowed when: not split or, split and role is central (i.e., not left)

## Power: sleep on halves to save battery
## https://zmk.dev/docs/config/power
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000