## Split keyboards
## https://zmk.dev/docs/config/system#split-keyboards
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

## USB interface for dongle (acts as USB keyboard)
CONFIG_ZMK_USB=y

## Display Configuratoin
## https://zmk.dev/docs/config/displays
# CONFIG_ZMK_DISPLAY=n

# ## Track words per minute
# CONFIG_ZMK_WPM=y


## PMW3610 Driver
## https://github.com/badjeff/zmk-pmw3610-driver
CONFIG_SPI=y
CONFIG_INPUT=y
#CONFIG_SPI_LOG_LEVEL_DBG=y